from distutils.core import setup
setup(  name='panddas',
        version='1.0',
        decription='Multi-dataset crystallographic analyses',
        author='Nicholas M Pearce',
        author_email='nicholas.pearce.0@gmail.com',
        package_dir={'':'lib-python'},
        packages=[    'pandda',
                    'pandda.jiffies',
                    'pandda.templates',
                    'Bamboo',
                    'Bamboo.Analysis',
                    'Bamboo.Common',
                    'Bamboo.Density',
                    'Bamboo.Macro',
                    'Bamboo.Maps',
                    'Bamboo.Misc',
                    'Bamboo.plot',
                    'Bamboo.Pymol',
                    'Bamboo.Rdkit',
                    'Bamboo.templates',
                    'Bamboo.Test',
                    'Bamboo.Utils',
                    'Bamboo.Wrappers',
                    'Bamboo.Xray',
                    'Giant',
                    'Giant.Graphics',
                    'Giant.Grid',
                    'Giant.jiffies',
                    'Giant.Ligands',
                    'Giant.Maths',
                    'Giant.Misc',
                    'Giant.Stats',
                    'Giant.Structure',
                    'Giant.templates',
                    'Giant.TestScripts',
                    'Giant.Utils',
                    'Giant.Xray',
        ]
      )
