import os, sys, glob
from setuptools import setup, find_packages

setup(  name                = 'panddas',
        version             = '1.0.2',
        description         = 'Multi-dataset crystallographic analyses',
        author              = 'Nicholas M Pearce',
        author_email        = 'nicholas.pearce.0@gmail.com',
        url                 = 'pandda.bitbucket.org',
        license             = 'CC BY-SA 4.0',
        install_requires    = ( 'pandas',
                                'jinja2',
                                'markupsafe',
                                'ascii_graph',
                                ),
        package_dir         = {'':'lib-python'},
        scripts             = glob.glob(os.path.join('bin','*')),
        packages            = find_packages(where   ='lib-python',
                                            exclude = ( 'phenix_pandda',    'phenix_pandda.*',
                                                        'prototypes',       'prototypes.*',
                                                        )
                                            ),
        classifiers         = ( 'Development Status :: 4 - Beta',
                                'Intended Audience :: Developers',
                                'Natural Language :: English',
                                'Programming Language :: Python',
                                'Programming Language :: Python :: 2.7',
                                'Topic :: Software Development :: Libraries :: Python Modules',
                                'Operating System :: Unix',
                                ),
        )
