(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Npearce, Welcome to Coot. 0.7 (revision 4459)  [with guile 1.8.8 embedded] [with python 2.7.0 embedded]")
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 15.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-maps 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-clipping-front -14.50)
(set-clipping-back -14.50)
(set-density-size 100.00)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-flag 1)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-run-state-file-status 0)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Nicholas. Welcome to Coot")
(set-display-lists-for-maps 0)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 10.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-maps 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-display-lists-for-maps 0)
(set-views-play-speed 20.00)
(handle-read-draw-molecule-with-recentre "reference.pdb" 1)
(set-add-terminal-residue-do-post-refine 1)
(set-terminal-residue-do-rigid-body-refine 0)
(use-graphics-interface-state)
(coot-checked-exit 0)
(clear-backups-maybe)
(save-state)
