filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Npearce, Welcome to Coot. 0.7 (revision 4459)  [with guile 1.8.8 embedded] [with python 2.7.0 embedded]")
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (15.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_maps (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_clipping_front (-14.50)
set_clipping_back (-14.50)
set_density_size (100.00)
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_flag (1)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_run_state_file_status (0)
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Nicholas. Welcome to Coot")
set_display_lists_for_maps (0)
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (10.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_maps (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_display_lists_for_maps (0)
set_views_play_speed (20.00)
handle_read_draw_molecule_with_recentre ("reference.pdb", 1)
set_add_terminal_residue_do_post_refine (1)
set_terminal_residue_do_rigid_body_refine (0)
use_graphics_interface_state ()
coot_checked_exit (0)
;; # DIRECT SCHEME ((clear-backups-maybe))
save_state ()
