(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Npearce, Welcome to Coot. (revision 5348)
[with guile 1.8.8 embedded]
[with python 2.7.8 embedded]")
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 10.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-clipping-front -14.50)
(set-clipping-back -14.50)
(set-density-size 10.00)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-show-symmetry-master 1)
(set-symmetry-shift-search-size 2)
(post-display-control-window)
(set-run-state-file-status 0)
(set-colour-map-rotation-on-read-pdb-flag 0)
(set-colour-map-rotation-for-map  0.00)
(use-graphics-interface-state)
(set-display-intro-string "Good morning Nicholas. Welcome to Coot")
(set-display-lists-for-maps 0)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 10.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-display-lists-for-maps 0)
(set-views-play-speed 20.00)
(handle-read-draw-molecule-with-recentre "reference.pdb" 1)
(set-add-terminal-residue-do-post-refine 1)
(set-terminal-residue-do-rigid-body-refine 0)
(make-and-draw-map "/home/npearce/LIGANDTEST/x529/1-apo/apo-refmac.mtz" "FWT" "PHWT" "" 0 0)
(handle-read-draw-molecule-with-recentre "/home/npearce/LIGANDTEST/x529/1-apo/apo-refmac.pdb" 1)
(graphics-molecule-bond-type 1)
(handle-read-draw-molecule-with-recentre "/home/npearce/LIGANDTEST/x529/2-ligand/ligand-grade.pdb" 0)
(graphics-molecule-bond-type 2)
(use-graphics-interface-state)
(graphics-molecule-bond-type 3)
(post-ligand-fit-gui)
(molecule-name 1)
(molecule-name 2)
(molecule-name 3)
(molecule-name 3)
(graphics-molecule-bond-type 4)
(post-ligand-fit-gui)
(molecule-name 1)
(molecule-name 2)
(molecule-name 3)
(molecule-name 4)
(molecule-name 3)
(molecule-name 4)
(set-rotation-centre 14.40 39.51 29.65)
(set-rotation-centre 14.40 39.51 29.65)
