filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Npearce, Welcome to Coot. (revision 5348)
[with guile 1.8.8 embedded]
[with python 2.7.8 embedded]")
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (10.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_clipping_front (-14.50)
set_clipping_back (-14.50)
set_density_size (10.00)
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_show_symmetry_master (1)
set_symmetry_shift_search_size (2)
post_display_control_window ()
set_run_state_file_status (0)
set_colour_map_rotation_on_read_pdb_flag (0)
set_colour_map_rotation_for_map ( 0.00)
use_graphics_interface_state ()
set_display_intro_string ("Good morning Nicholas. Welcome to Coot")
set_display_lists_for_maps (0)
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (10.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_display_lists_for_maps (0)
set_views_play_speed (20.00)
handle_read_draw_molecule_with_recentre ("reference.pdb", 1)
set_add_terminal_residue_do_post_refine (1)
set_terminal_residue_do_rigid_body_refine (0)
make_and_draw_map ("/home/npearce/LIGANDTEST/x529/1-apo/apo-refmac.mtz", "FWT", "PHWT", "", 0, 0)
handle_read_draw_molecule_with_recentre ("/home/npearce/LIGANDTEST/x529/1-apo/apo-refmac.pdb", 1)
graphics_molecule_bond_type (1)
handle_read_draw_molecule_with_recentre ("/home/npearce/LIGANDTEST/x529/2-ligand/ligand-grade.pdb", 0)
graphics_molecule_bond_type (2)
use_graphics_interface_state ()
graphics_molecule_bond_type (3)
;; # DIRECT SCHEME ((post-ligand-fit-gui))
molecule_name (1)
molecule_name (2)
molecule_name (3)
molecule_name (3)
graphics_molecule_bond_type (4)
;; # DIRECT SCHEME ((post-ligand-fit-gui))
molecule_name (1)
molecule_name (2)
molecule_name (3)
molecule_name (4)
molecule_name (3)
molecule_name (4)
set_rotation_centre (14.40, 39.51, 29.65)
set_rotation_centre (14.40, 39.51, 29.65)
